### ISSUE TITLE
Panic after update from 0.3.3 to 0.4.0

### ISSUE THREAD

**Issue by nazar-pc** [irrustible/async-oneshot#11] opened 2020-10-10 14:50 UTC
I've checked changelog and looks like it should not have failed:
<details>

```
thread '<unnamed>' panicked at 'assertion failed: !self.state().recv()', /home/nazar-pc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:10:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:50
  14: async_oneshot::inner::Inner<T>::set_recv
             at /home/nazar-pc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:10
  15: <async_oneshot::receiver::Receiver<T> as core::future::future::Future>::poll
             at /home/nazar-pc/.cargo/registry/src/github.com-1ecc6299db9ec823/async-oneshot-0.4.0/src/receiver.rs:55
  16: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/nazar-pc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.1/src/future.rs:526
  17: async_executor::Executor::run::{{closure}}
             at /home/nazar-pc/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.3.0/src/lib.rs:214
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/nazar-pc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  19: futures_lite::future::block_on::{{closure}}
             at /home/nazar-pc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.1/src/future.rs:89
  20: std::thread::local::LocalKey<T>::try_with
             at /home/nazar-pc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  21: std::thread::local::LocalKey<T>::with
             at /home/nazar-pc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  22: futures_lite::future::block_on
             at /home/nazar-pc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.1/src/future.rs:79
  23: mediasoup::worker::tests::worker_test::{{closure}}
             at src/worker.rs:638
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

Is this some kind of race condition?

Here is the piece of code that uses it and fails:
https://github.com/nazar-pc/mediasoup/blob/c509f86ee0d18387db516d07a4f19023397d76f9/rust/src/worker.rs#L416-L446

If you need to reproduce it, make sure to run `npm install` in the root of that repo, it uses C++ worker build using some NPM scripts.

**Comment by jjl** [comment] 2020-10-10 15:43
This is weird. I've had a look through my code and I can't explain it. I'll give reproducing it in your repository a shot.

**Comment by jjl** [comment] 2020-10-10 15:48
I can't get past this error:

```
pm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
```

I tried `npm install`, but that did not fix it.

**Comment by nazar-pc** [comment] 2020-10-10 15:50
Should work if you are in the root of the repo (or there will be a different error).
Also make sure to use `rust` branch, this is where I'm working on a library port from TypeScript to Rust.

**Comment by jjl** [comment] 2020-10-10 15:52
This does not work on the `rust` branch either. npom 6.14.6

**Comment by nazar-pc** [comment] 2020-10-10 15:53
What error do you get?
You may also need to specify python binary depending on OS as `PYTHON=python3 npm i`

**Comment by jjl** [comment] 2020-10-10 15:56
I get the same error as above. If i try `npm shrinkwrap` i get a different one:

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Cannot read property '@types/node' of undefined
```

I installed python2 because it complained about being unable to find a `python` binary before.

**Comment by jjl** [comment] 2020-10-10 15:57
PYTHON=python3 made no difference either.

**Comment by nazar-pc** [comment] 2020-10-10 15:58
With `npm install` error should not be the same, it doesn't care about lock file.

**Comment by jjl** [comment] 2020-10-10 15:58
npm install runs fine. `npm ci` following it is what i'm posting errors from

**Comment by nazar-pc** [comment] 2020-10-10 16:00
If you did `npm install` successfully that is all you need.
Then just:
```
cd rust
cargo test
```

Once that works, try to update `async-oneshot`.

**Comment by jjl** [comment] 2020-10-10 16:01
aha!

now i'm on this error running the tests:

```
error[E0432]: unresolved import `crate::router::data_consumer`
  --> /home/james/code/forks/mediasoup/rust/src/router/transport.rs:19:20
   |
19 | use crate::router::data_consumer::DataConsumerType;
   |                    ^^^^^^^^^^^^^ could not find `data_consumer` in `router`

error[E0432]: unresolved import `crate::router::data_consumer`
  --> /home/james/code/forks/mediasoup/rust/src/router/webrtc_transport.rs:13:20
   |
13 | use crate::router::data_consumer::DataConsumerType;
   |                    ^^^^^^^^^^^^^ could not find `data_consumer` in `router`

error[E0432]: unresolved import `crate::router::data_producer`
  --> /home/james/code/forks/mediasoup/rust/src/router/webrtc_transport.rs:14:20
   |
14 | use crate::router::data_producer::{DataProducerOptions, DataProducerType};
   |                    ^^^^^^^^^^^^^ could not find `data_producer` in `router`

error: aborting due to 3 previous errors
```

**Comment by nazar-pc** [comment] 2020-10-10 16:03
Pushed fix for that, sorry, still work in progress :slightly_smiling_face:

**Comment by jjl** [comment] 2020-10-10 16:04
almost :)

error[E0432]: unresolved import `crate::router::data_consumer`
  --> /home/james/code/forks/mediasoup/rust/src/router/transport.rs:19:20
   |
19 | use crate::router::data_consumer::DataConsumerType;
   |                    ^^^^^^^^^^^^^ could not find `data_consumer` in `router`

error[E0432]: unresolved import `crate::router::data_consumer`
  --> /home/james/code/forks/mediasoup/rust/src/router/webrtc_transport.rs:13:20
   |
13 | use crate::router::data_consumer::DataConsumerType;
   |                    ^^^^^^^^^^^^^ could not find `data_consumer` in `router`

error[E0432]: unresolved import `crate::router::data_producer`
  --> /home/james/code/forks/mediasoup/rust/src/router/webrtc_transport.rs:14:20
   |
14 | use crate::router::data_producer::{DataProducerOptions, DataProducerType};
   |                    ^^^^^^^^^^^^^ could not find `data_producer` in `router`

error: aborting due to 3 previous errors

**Comment by nazar-pc** [comment] 2020-10-10 16:05
Please pull one more time

**Comment by jjl** [comment] 2020-10-10 16:06
okay, i'm in the matrix! let me play around with it with my local copy of oneshot.

**Comment by jjl** [comment] 2020-10-10 16:20
Okay, I've found it. It was the debug_assert checking the receiver had not already been set. So in production, it would not have crashed, at least.

**Comment by jjl** [comment] 2020-10-10 16:24
v0.4.1 is released with this (and a related case where you could wake the sender multiple times during wait) patched.

**Closed by jjl** 2020-10-10 16:24 UTC

**Comment by nazar-pc** [comment] 2020-10-10 16:28
Wow, that was fast, thanks!

**Comment by jjl** [comment] 2020-10-10 16:34
I had that heartsink moment when i saw this issue and thought i'd better do something about the feeling :)
